export const STORE_SENT_MESSAGE = 'STORE_SENT_MESSAGE';
export const ADD_RECEIVED_MESSAGE = 'ADD_RECEIVED_MESSAGE';

export const UPDATE_CONFIG_SELECTED_OPTION = 'UPDATE_CONFIG_SELECTED_OPTION';
export const UPDATE_CONFIG_STRING_OPTION = 'UPDATE_CONFIG_STRING_OPTION';
export const RESET_CONFIG_TO_DEFAULTS = 'RESET_CONFIG_TO_DEFAULTS';
