export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE';
export const ADD_RECEIVED_MESSAGE = 'ADD_RECEIVED_MESSAGE';

export const UPDATE_CONFIG_SELECTED_OPTION = 'UPDATE_CONFIG_SELECTED_OPTION';
export const UPDATE_CONFIG_STRING_OPTION = 'UPDATE_CONFIG_STRING_OPTION';
export const RESET_ALL_CONFIG_OPTIONS = 'RESET_ALL_CONFIG_OPTIONS';
